apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sxui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-sxui@sha256:dc6c58030f5d068adf122c23fbee64109083a1462ba422d0949a965eb03e7a77
        name: my-nodejs
        resources: {}
status: {}
